### PR TITLE
address multiple typescript errors

### PR DESCRIPTION
**Pull request by bpow**
This addresses only part of #4 by setting an index for the settings type and by explicitly using `any` in `search()`

### CODE REVIEW

**Comment by bpow** [comment]
At this point, the referenced pull request clears up almost all of the errors emitted by tsc. The only remaining errors are related to references to Showdown-- I'm not sure how to handle these since it looks like you typically include/import this elsewhere.

I've made every effort to keep behavior identical while just making tsc happy. One commit that you might want to look at more closely is 7f8d875 since I'm not sure how the gatheredResults structure was being used by external code. I'm happy to squash the commits, but kept them separate for now since that may make it easier to see what I was doing.

I'm fairly new to typescript, so I'm not sure how idiomatic these changes are, but it was a good way to familiarize myself with this code and your examples (I'm specifically looking into the ClinGen example with thoughts to extend to other types of guided annotation).

**Comment by judell** [comment]
Thanks so much, @bpow! I'll review and run the tests.

> I'm specifically looking into the ClinGen example with thoughts to extend to other types of guided annotation

I'll be interested to know your thoughts on that. I'm certain there will be a need for variants of that guided workflow, and a couple of related examples will clarify how to generalize from the ClinGen example. The state machine may be overkill, but in any case would currently require more coding than ideally would be necessary, so I had made a note to myself to look for a more declarative approach next time around.

**Review by judell — COMMENTED** [review]
2b25cc0 

> This turns out to be problematic because although several things are declared as Map<string, string>, they are really just Object and need to work with JSON.parse and JSON.stringify (which Map doesn't).
> 
> Because the Object does not have get and set as Map does, this test fails: https://github.com/judell/hlib/blob/master/test.html#L409.
> 
> I'm not sure what to do here. I guess the fallback would be to stop trying to pacify TypeScript, let these objects be plain objects, and just tolerate the implicit any warning. It would be nice to describe them in a more precise way, though, so if you see a better way I'm all ears.
> 
> This was the only change that triggered a test failure. I'm adding another test for displayKeysAndHiddenValues, and will aim to add more tests to probe for other things we might be missing.

964e423

> Yeah, that's just me noticing that when there are no params there needs to be something there, and it evidently doesn't need to be (). But probably should be :-)

Thanks again for your help with this. I have found navigating the TS/JS boundary to be rather tricky and I really appreciate the extra eyes and hands.

**Comment by judell** [comment]
> I'm specifically looking into the ClinGen example with thoughts to extend to other types of guided annotation

I accidentally deleted a prior comment about this, which was something like: Great, I hope you'll pursue that, I'm not too happy with how that app handles workflow, a few more use cases would help clarify matters.

**Comment by judell** [comment]
@bpow thanks so much for your intervention here. I would up incorporating your changes into https://github.com/judell/hlib/commit/ef61a7baf7cebf625c4e249d686754ecfb7d57fb along with other things that I found as I worked through your changes.

Along the way I improved the tests, but the real acid test is to use https://github.com/judell/facet in conjunction with this library, as I've documented here: https://github.com/judell/hlib/blob/master/README.md#running-tests

The `showdown` complaint remains, and I'm open to suggestions there. FWIW I don't want to include `showdown` in the bundle created by the build, would rather just source it into apps that use this library in the way that `facet` does. 
 
I'm kind of on the fence w/respect to the benefit of having done both `facet` and `hlib` in TypeScript. In principle I'm a huge fan of TypeScript, in practice it feels like I've had to work awfully hard to reap the benefits. 

In any event, things are cleaner now, and I'm really glad you made that happen.

**Pull request closed without merging**
